### ISSUE TITLE
Can you add a version for 1.20.2?

### ISSUE THREAD

**Issue by ActivateClosur3** [ibimschder/Trailer-Edition#1]
thanks

**Comment by ibimschder** [comment]
Hello (sorry if this took long I don't check GitHub that often) the problem is many mods are only available for 1.20.1 I can try to make a version for 1.20.2 but It could happen that some mods are missing or not working properly

But I will try for you

**Comment by ibimschder** [comment]
Hello I made the 1.20.2 version. 
thanks for the suggestion. 

The only problem that is present is that the Fresh Animations pack is not working properly
